api_version = "2025-07"

[[extensions]]
name = "bundle-expander-transform"
handle = "bundle-expander"
type = "function"
uid = "aabe8378-f63a-8805-3145-53fcaf889cec3910e3d6"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"